version: '3.9'
networks:
  devnet:
    driver: bridge
services:
  nexus:
   image: sonatype/nexus3
   container_name: nexus
   ports:
    - 8081:8081
   networks:
    - devnet
   volumes:
    - /opt/nexus:/var/lib/nexus

  jenkins:
   image: jenkins/jenkins
   container_name: jenkins
   stdin_open: true
   tty: true
   privileged: true
   user: root
   ports:
    - 8080:8080
    - 5000:5000
    - 50000:50000
   volumes:
    - ~/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    
   sonardb:
   image: postgres
   networks:
    - devnet
   container_name: postgres
   restart: unless-stopped
   environment:
    - POSTGRES_USER=sonarpost
    - POSTGRES_PASSWORD=sonar
    - POSTGRESQL_DB=sonar
   ports:
    - "5432:5432"
   volumes:
    - postgresql_data:/var/lib/postgresql/data
    
  sonarqube:
    image: sonarqube
    restart: unless-stopped
    container_name: sonarqube
    ports:
    - 9000:9000
    - 9092:9092
    networks:
      - devnet
    depends_on:
      - sonardb
    environment:
     - sonar.jdbc.username=sonar
     - sonar.jdbc.url=jdbc:postgresql://sonardb/sonar
     - sonar.jdbc.password=sonar
    volumes:
     - sonarqube_conf:/opt/sonarqube/conf
     - sonarqube_data:/opt/sonarqube/data
     - sonarqube_extensions:/opt/sonarqube/extensions
     - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
     - sonarqube_logs:/opt/sonarqube/logs
     
  tomcat:
   image: tomcat
   ports: 
    - "8011:8080"
   networks:
    - devnet
   container_name: tomcat
   volumes:
    - ./logs/:/urs/local/tomcat/logs/

  selenium-hub:
   image: selenium/hub
   container_name: selenium-hub
   ports:
    - "4442:4442"
    - "4443:4443" 
    - "4444:4444"

  selenium-node-firefox:
   image: selenium/node-firefox
   container_name: selenium-node-firefox
   depends_on:
    - selenium-hub
   environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   ports:
    - "6901:5900"

  selenium-node-chrome:
   image: selenium/node-chrome
   container_name: selenium-node-chrome
   depends_on:
    - selenium-hub
   environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   ports:
    - "6902:5900"

  volumes:
   postgresql_data:
   sonarqube_bundled-plugins:
   sonarqube_conf:
   sonarqube_data:
   sonarqube_db:
   sonarqube_extensions:
   sonarqube_logs:
