version: '3.9'
networks:
  devnet:
    driver: bridge
services:
  nexus:
   image: sonatype/nexus3
   container_name: nexus
   ports:
    - 8081:8081
   networks:
    - devnet
   volumes:
    - /opt/nexus:/var/lib/nexus

  jenkins:
   image: jenkins/jenkins
   container_name: jenkins
   user: jenkins
   stdin_open: true
   tty: true
   privileged: true
   expose:
   - 2376
   ports:
    - 8080:8080
    - 5000:5000
    - 50000:50000
   environment: 
    - DOCKER_TLS_CERTDIR="/certs"
   networks:
    - devnet
   volumes:
    - /jenkins-data:/var/jenkins_home
    - /jenkins-docker-certs:/certs/client
    
  sonardb:
   image: postgres
   networks:
    - devnet
   container_name: postgres
   restart: always
   environment:
    - POSTGRES_USER=adam
    - POSTGRES_PASSWORD=123
    - POSTGRESQL_DB=sonar
   ports:
    - "5432:5432"
   volumes:
    - /var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    stdin_open: true
    tty: true
    privileged: true
    ports:
    - 9000:9000
    networks:
      - devnet
    depends_on:
      - sonardb
    links:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL="jdbc:postgresql://sonardb:5432/sonar"
     - SONARQUBE_JDBC_USERNAME=adam
     - SONARQUBE_JDBC_PASSWORD=123
    
  tomcat:
   image: tomcat
   ports: 
    - "8011:8080"
   networks:
    - devnet
   container_name: tomcat
   volumes:
    - ./logs/:/urs/local/tomcat/logs/

  selenium-hub:
   image: selenium/hub
   container_name: selenium-hub
   ports:
    - "4442:4442"
    - "4443:4443" 
    - "4444:4444"

  selenium-node-firefox:
   image: selenium/node-firefox
   container_name: selenium-node-firefox
   depends_on:
    - selenium-hub
   environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   ports:
    - "6901:5900"

  selenium-node-chrome:
   image: selenium/node-chrome
   container_name: selenium-node-chrome
   depends_on:
    - selenium-hub
   environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   ports:
    - "6902:5900"
